#ifndef SOFA_PLUGIN_SOFAMINIMAL3_H
#define SOFA_PLUGIN_SOFAMINIMAL3_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_SOFAMINIMAL3_PLUGIN
#  define SOFA_SOFAMINIMAL3_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAMINIMAL3_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif


#endif // SOFA_PLUGIN_SOFAMINIMAL3_H
