#ifndef SOFA_PLUGIN_SOFAMINIMAL2_H
#define SOFA_PLUGIN_SOFAMINIMAL2_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_SOFAMINIMAL2_PLUGIN
#  define SOFA_SOFAMINIMAL2_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAMINIMAL2_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif


#endif // SOFA_PLUGIN_SOFAMINIMAL2_H
