#ifndef SOFA_PLUGIN_SOFAMINIMAL_H
#define SOFA_PLUGIN_SOFAMINIMAL_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_SOFAMINIMALEXT_PLUGIN
#  define SOFA_SOFAMINIMALEXT_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAMINIMALEXT_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif


#endif // SOFA_PLUGIN_SOFAMINIMAL_H
