#ifndef SOFA_PLUGIN_SOFANG_H
#define SOFA_PLUGIN_SOFANG_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_SOFANGEXT_PLUGIN
#  define SOFA_SOFANGEXT_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFANGEXT_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif


#endif // SOFA_PLUGIN_SOFANG_H
