#ifndef SOFA_PLUGIN_SOFAMINIMAL0_H
#define SOFA_PLUGIN_SOFAMINIMAL0_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_SOFAMINIMAL0_PLUGIN
#  define SOFA_SOFAMINIMAL0_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAMINIMAL0_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif


#endif // SOFA_PLUGIN_SOFAMINIMAL0_H
