#ifndef SOFA_PLUGIN_SOFAMINIMAL_H
#define SOFA_PLUGIN_SOFAMINIMAL_H


#include <sofa/helper/system/config.h>

#ifdef SOFA_BUILD_SOFAMINIMAL_PLUGIN
#  define SOFA_SOFAMINIMAL_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define SOFA_SOFAMINIMAL_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif


#endif // SOFA_PLUGIN_SOFAMINIMAL_H
